2025-02-25T03:23:11.6801320Z ##[group]Run pytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-25T03:23:11.6802400Z [36;1mpytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-25T03:23:11.6882610Z shell: /bin/bash -l {0}
2025-02-25T03:23:11.6882850Z env:
2025-02-25T03:23:11.6883010Z   CACHE_NUMBER: 0
2025-02-25T03:23:11.6883540Z   PYTEST_FLAGS: --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-25T03:23:11.6884090Z   CODECOV_TOKEN: 
2025-02-25T03:23:11.6884280Z   MAMBA_ROOT_PREFIX: /Users/runner/micromamba
2025-02-25T03:23:11.6884580Z   MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
2025-02-25T03:23:11.6885120Z   CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
2025-02-25T03:23:11.6885480Z ##[endgroup]
2025-02-25T03:23:31.3813630Z ============================= test session starts ==============================
2025-02-25T03:23:31.3814430Z platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-25T03:23:31.3814830Z rootdir: /Users/runner/work/tardis/tardis
2025-02-25T03:23:31.3815130Z configfile: pyproject.toml
2025-02-25T03:23:31.3815600Z plugins: cov-5.0.0, html-4.1.1, metadata-3.1.1, doctestplus-1.2.1, anyio-4.4.0
2025-02-25T03:23:31.3816190Z collected 1787 items / 1 error / 1785 deselected / 2 selected
2025-02-25T03:23:31.3816560Z 
2025-02-25T03:23:31.3816840Z ==================================== ERRORS ====================================
2025-02-25T03:23:31.3817410Z __ ERROR collecting tardis/energy_input/tests/test_gamma_ray_packet_source.py __
2025-02-25T03:23:31.3818150Z ImportError while importing test module '/Users/runner/work/tardis/tardis/tardis/energy_input/tests/test_gamma_ray_packet_source.py'.
2025-02-25T03:23:31.3818790Z Hint: make sure your test modules/packages have valid Python names.
2025-02-25T03:23:31.3819240Z Traceback:
2025-02-25T03:23:31.3819580Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-25T03:23:31.3820090Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-25T03:23:31.3820530Z tardis/energy_input/tests/test_gamma_ray_packet_source.py:4: in <module>
2025-02-25T03:23:31.3820970Z     from tardis.energy_input.gamma_ray_packet_source import RadioactivePacketSource
2025-02-25T03:23:31.3821780Z E   ImportError: cannot import name 'RadioactivePacketSource' from 'tardis.energy_input.gamma_ray_packet_source' (/Users/runner/work/tardis/tardis/tardis/energy_input/gamma_ray_packet_source.py)
2025-02-25T03:23:31.3822420Z =============================== warnings summary ===============================
2025-02-25T03:23:31.3822760Z tardis/io/configuration/config_validator.py:6
2025-02-25T03:23:31.3823080Z tardis/io/configuration/config_validator.py:6
2025-02-25T03:23:31.3823720Z   /Users/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-25T03:23:31.3824170Z   
2025-02-25T03:23:31.3825250Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-25T03:23:31.3826290Z 
2025-02-25T03:23:31.3826550Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-25T03:23:31.3827160Z   /Users/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-25T03:23:31.3827680Z   
2025-02-25T03:23:31.3827950Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-25T03:23:31.3828400Z   given by the platformdirs library.  To remove this warning and
2025-02-25T03:23:31.3829520Z   see the appropriate new directories, set the environment variable
2025-02-25T03:23:31.3829990Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-25T03:23:31.3830370Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-25T03:23:31.3830700Z 
2025-02-25T03:23:31.3830860Z tardis/plasma/properties/__init__.py:17
2025-02-25T03:23:31.3831290Z   /Users/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-25T03:23:31.3831770Z   
2025-02-25T03:23:31.3832350Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-25T03:23:31.3832910Z 
2025-02-25T03:23:31.3833130Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-25T03:23:31.3833640Z 
2025-02-25T03:23:31.3833860Z ---------- coverage: platform darwin, python 3.12.4-final-0 ----------
2025-02-25T03:23:31.3834210Z Coverage HTML written to dir coverage_html_report
2025-02-25T03:23:31.3834590Z Coverage XML written to file coverage.xml
2025-02-25T03:23:31.3834810Z 
2025-02-25T03:23:31.3834910Z =========================== short test summary info ============================
2025-02-25T03:23:31.3835350Z ERROR tardis/energy_input/tests/test_gamma_ray_packet_source.py
2025-02-25T03:23:31.3835760Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-25T03:23:31.3836220Z ================ 1785 deselected, 4 warnings, 1 error in 8.12s =================
2025-02-25T03:23:32.0473270Z ##[error]Process completed with exit code 2.
