2025-01-20T13:51:59.6513908Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-01-20T13:51:59.6515226Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-01-20T13:51:59.6542889Z shell: /usr/bin/bash -l {0}
2025-01-20T13:51:59.6543143Z env:
2025-01-20T13:51:59.6543321Z   CACHE_NUMBER: 0
2025-01-20T13:51:59.6543942Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-01-20T13:51:59.6544580Z   CODECOV_TOKEN: 
2025-01-20T13:51:59.6544792Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-01-20T13:51:59.6545094Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-01-20T13:51:59.6545447Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-01-20T13:51:59.6545793Z ##[endgroup]
2025-01-20T13:52:15.5647397Z ============================= test session starts ==============================
2025-01-20T13:52:15.5648142Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-01-20T13:52:15.5648752Z rootdir: /home/runner/work/tardis/tardis
2025-01-20T13:52:15.5649194Z configfile: pyproject.toml
2025-01-20T13:52:15.5649764Z plugins: anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1, metadata-3.1.1
2025-01-20T13:52:15.5650470Z collected 1768 items / 1 error / 1766 deselected / 2 selected
2025-01-20T13:52:15.5650865Z 
2025-01-20T13:52:15.5651033Z ==================================== ERRORS ====================================
2025-01-20T13:52:15.5651944Z ___________ ERROR collecting tardis/io/logger/tests/test_logging.py ____________
2025-01-20T13:52:15.5652851Z ImportError while importing test module '/home/runner/work/tardis/tardis/tardis/io/logger/tests/test_logging.py'.
2025-01-20T13:52:15.5653895Z Hint: make sure your test modules/packages have valid Python names.
2025-01-20T13:52:15.5654542Z Traceback:
2025-01-20T13:52:15.5655054Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-01-20T13:52:15.5655805Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-01-20T13:52:15.5656383Z tardis/io/logger/tests/test_logging.py:7: in <module>
2025-01-20T13:52:15.5656913Z     from tardis.io.logger.logger import LOGGING_LEVELS
2025-01-20T13:52:15.5657392Z tardis/io/logger/logger.py:5: in <module>
2025-01-20T13:52:15.5657799Z     import panel as pn
2025-01-20T13:52:15.5658163Z E   ModuleNotFoundError: No module named 'panel'
2025-01-20T13:52:15.5658652Z =============================== warnings summary ===============================
2025-01-20T13:52:15.5659149Z tardis/io/configuration/config_validator.py:6
2025-01-20T13:52:15.5659599Z tardis/io/configuration/config_validator.py:6
2025-01-20T13:52:15.5660383Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-01-20T13:52:15.5661322Z   
2025-01-20T13:52:15.5663271Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-01-20T13:52:15.5665209Z 
2025-01-20T13:52:15.5665589Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-01-20T13:52:15.5666651Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-01-20T13:52:15.5667449Z   
2025-01-20T13:52:15.5667805Z   Jupyter is migrating its paths to use standard platformdirs
2025-01-20T13:52:15.5668387Z   given by the platformdirs library.  To remove this warning and
2025-01-20T13:52:15.5669002Z   see the appropriate new directories, set the environment variable
2025-01-20T13:52:15.5669920Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-01-20T13:52:15.5670507Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-01-20T13:52:15.5671225Z 
2025-01-20T13:52:15.5671462Z tardis/transport/montecarlo/tests/test_montecarlo.py:557
2025-01-20T13:52:15.5672459Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:557: PytestUnknownMarkWarning:
2025-01-20T13:52:15.5673328Z   
2025-01-20T13:52:15.5674226Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-01-20T13:52:15.5675155Z 
2025-01-20T13:52:15.5675386Z tardis/transport/montecarlo/tests/test_montecarlo.py:584
2025-01-20T13:52:15.5676336Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:584: PytestUnknownMarkWarning:
2025-01-20T13:52:15.5677160Z   
2025-01-20T13:52:15.5678024Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-01-20T13:52:15.5678897Z 
2025-01-20T13:52:15.5679120Z tardis/transport/montecarlo/tests/test_montecarlo.py:605
2025-01-20T13:52:15.5680072Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:605: PytestUnknownMarkWarning:
2025-01-20T13:52:15.5680880Z   
2025-01-20T13:52:15.5681870Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-01-20T13:52:15.5682759Z 
2025-01-20T13:52:15.5683055Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-01-20T13:52:15.5683493Z 
2025-01-20T13:52:15.5683751Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-01-20T13:52:15.5684317Z Coverage HTML written to dir coverage_html_report
2025-01-20T13:52:15.5684787Z Coverage XML written to file coverage.xml
2025-01-20T13:52:15.5685090Z 
2025-01-20T13:52:15.5685279Z =========================== short test summary info ============================
2025-01-20T13:52:15.5685785Z ERROR tardis/io/logger/tests/test_logging.py
2025-01-20T13:52:15.5686295Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-01-20T13:52:15.5686880Z ================ 1766 deselected, 6 warnings, 1 error in 9.06s =================
2025-01-20T13:52:16.2927399Z ##[error]Process completed with exit code 2.
