2025-02-23T16:24:07.0780730Z ##[group]Run pytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-23T16:24:07.0781900Z [36;1mpytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-23T16:24:07.0841380Z shell: /bin/bash -l {0}
2025-02-23T16:24:07.0841690Z env:
2025-02-23T16:24:07.0841890Z   CACHE_NUMBER: 0
2025-02-23T16:24:07.0842490Z   PYTEST_FLAGS: --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-23T16:24:07.0843290Z   CODECOV_TOKEN: 
2025-02-23T16:24:07.0843530Z   MAMBA_ROOT_PREFIX: /Users/runner/micromamba
2025-02-23T16:24:07.0843910Z   MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
2025-02-23T16:24:07.0844260Z   CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
2025-02-23T16:24:07.0844730Z ##[endgroup]
2025-02-23T16:24:21.6607770Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:21.6707120Z 
2025-02-23T16:24:21.6752190Z invalid escape sequence '\s'
2025-02-23T16:24:21.6752580Z 
2025-02-23T16:24:21.6752990Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:21.6753400Z 
2025-02-23T16:24:21.6753590Z invalid escape sequence '\s'
2025-02-23T16:24:21.6753820Z 
2025-02-23T16:24:21.6919140Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:24:21.6919600Z 
2025-02-23T16:24:21.6919720Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:21.6920070Z 
2025-02-23T16:24:23.8663810Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:23.8664740Z 
2025-02-23T16:24:23.8665200Z invalid escape sequence '\s'
2025-02-23T16:24:23.8666530Z 
2025-02-23T16:24:26.3620650Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:26.3621180Z 
2025-02-23T16:24:26.3621400Z invalid escape sequence '\s'
2025-02-23T16:24:26.3621720Z 
2025-02-23T16:24:27.2901030Z <unknown>:143: SyntaxWarning:
2025-02-23T16:24:27.2943490Z 
2025-02-23T16:24:27.2944230Z invalid escape sequence '\s'
2025-02-23T16:24:27.2944510Z 
2025-02-23T16:24:27.2944970Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:27.2945360Z 
2025-02-23T16:24:27.2945540Z invalid escape sequence '\s'
2025-02-23T16:24:27.2945770Z 
2025-02-23T16:24:27.3403450Z /Users/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: SyntaxWarning:
2025-02-23T16:24:27.3404040Z 
2025-02-23T16:24:27.3404310Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:27.3404540Z 
2025-02-23T16:24:29.2052590Z ============================= test session starts ==============================
2025-02-23T16:24:29.2053700Z platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-23T16:24:29.2054620Z rootdir: /Users/runner/work/tardis/tardis
2025-02-23T16:24:29.2055360Z configfile: pyproject.toml
2025-02-23T16:24:29.2056160Z plugins: cov-5.0.0, html-4.1.1, metadata-3.1.1, doctestplus-1.2.1, anyio-4.4.0
2025-02-23T16:24:29.2057370Z collected 1795 items / 1 error / 1793 deselected / 2 selected
2025-02-23T16:24:29.2058020Z 
2025-02-23T16:24:29.2058540Z ==================================== ERRORS ====================================
2025-02-23T16:24:29.2059620Z _____ ERROR collecting tardis/io/model/readers/tests/test_artis_readers.py _____
2025-02-23T16:24:29.2060270Z tardis/io/model/readers/tests/test_artis_readers.py:12: in <module>
2025-02-23T16:24:29.2060640Z     @pytest.fixture
2025-02-23T16:24:29.2060880Z E   NameError: name 'pytest' is not defined
2025-02-23T16:24:29.2061320Z ------------------------------- Captured stdout --------------------------------
2025-02-23T16:24:29.2061970Z [[1mpy.warnings         [0m][[1;33mWARNING[0m]  
2025-02-23T16:24:29.2062590Z 	/Users/runner/work/tardis/tardis/tardis/io/model/readers/tests/test_artis_readers.py:58: PytestAssertRewriteWarning:
2025-02-23T16:24:29.2065090Z 
2025-02-23T16:24:29.2065220Z assertion is always true, perhaps remove parentheses?
2025-02-23T16:24:29.2065490Z 
2025-02-23T16:24:29.2065710Z  ([1mwarnings.py[0m:112)
2025-02-23T16:24:29.2066010Z =============================== warnings summary ===============================
2025-02-23T16:24:29.2066420Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:24:29.2066720Z tardis/io/configuration/config_validator.py:6
2025-02-23T16:24:29.2067310Z   /Users/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-23T16:24:29.2067860Z   
2025-02-23T16:24:29.2068920Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-23T16:24:29.2070280Z 
2025-02-23T16:24:29.2070540Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-23T16:24:29.2071160Z   /Users/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-23T16:24:29.2071620Z   
2025-02-23T16:24:29.2071890Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-23T16:24:29.2072360Z   given by the platformdirs library.  To remove this warning and
2025-02-23T16:24:29.2072720Z   see the appropriate new directories, set the environment variable
2025-02-23T16:24:29.2073210Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-23T16:24:29.2073650Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-23T16:24:29.2073940Z 
2025-02-23T16:24:29.2074100Z tardis/io/model/readers/artis.py:143
2025-02-23T16:24:29.2074610Z   /Users/runner/work/tardis/tardis/tardis/io/model/readers/artis.py:143: SyntaxWarning:
2025-02-23T16:24:29.2075020Z   
2025-02-23T16:24:29.2075330Z   invalid escape sequence '\s'
2025-02-23T16:24:29.2075460Z 
2025-02-23T16:24:29.2075690Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-23T16:24:29.2076000Z 
2025-02-23T16:24:29.2076210Z ---------- coverage: platform darwin, python 3.12.4-final-0 ----------
2025-02-23T16:24:29.2076600Z Coverage HTML written to dir coverage_html_report
2025-02-23T16:24:29.2076990Z Coverage XML written to file coverage.xml
2025-02-23T16:24:29.2077220Z 
2025-02-23T16:24:29.2077330Z =========================== short test summary info ============================
2025-02-23T16:24:29.2077870Z ERROR tardis/io/model/readers/tests/test_artis_readers.py - NameError: name 'pytest' is not defined
2025-02-23T16:24:29.2078310Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-23T16:24:29.2078660Z ================ 1793 deselected, 4 warnings, 1 error in 9.38s =================
2025-02-23T16:24:30.1686790Z ##[error]Process completed with exit code 2.
