2025-01-14T20:56:31.5572070Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-01-14T20:56:31.5573365Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-01-14T20:56:31.5599953Z shell: /usr/bin/bash -l {0}
2025-01-14T20:56:31.5600217Z env:
2025-01-14T20:56:31.5600386Z   CACHE_NUMBER: 0
2025-01-14T20:56:31.5600992Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-01-14T20:56:31.5601637Z   CODECOV_TOKEN: 
2025-01-14T20:56:31.5601860Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-01-14T20:56:31.5602165Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-01-14T20:56:31.5602518Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-01-14T20:56:31.5602848Z ##[endgroup]
2025-01-14T20:56:47.3212927Z ============================= test session starts ==============================
2025-01-14T20:56:47.3213682Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-01-14T20:56:47.3214291Z rootdir: /home/runner/work/tardis/tardis
2025-01-14T20:56:47.3214823Z configfile: pyproject.toml
2025-01-14T20:56:47.3215592Z plugins: anyio-4.4.0, doctestplus-1.2.1, cov-5.0.0, html-4.1.1, metadata-3.1.1
2025-01-14T20:56:47.3216546Z collected 1788 items / 1 error / 2 deselected / 1786 selected
2025-01-14T20:56:47.3217059Z 
2025-01-14T20:56:47.3217275Z ==================================== ERRORS ====================================
2025-01-14T20:56:47.3218096Z _______________ ERROR collecting tardis/plasma/equilibrium/tests _______________
2025-01-14T20:56:47.3219198Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-01-14T20:56:47.3220202Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-01-14T20:56:47.3220722Z <frozen importlib._bootstrap>:1387: in _gcd_import
2025-01-14T20:56:47.3221104Z     ???
2025-01-14T20:56:47.3221404Z <frozen importlib._bootstrap>:1360: in _find_and_load
2025-01-14T20:56:47.3221784Z     ???
2025-01-14T20:56:47.3222115Z <frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
2025-01-14T20:56:47.3222532Z     ???
2025-01-14T20:56:47.3222821Z <frozen importlib._bootstrap>:935: in _load_unlocked
2025-01-14T20:56:47.3223204Z     ???
2025-01-14T20:56:47.3223760Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
2025-01-14T20:56:47.3224428Z     exec(co, module.__dict__)
2025-01-14T20:56:47.3224847Z tardis/plasma/equilibrium/tests/conftest.py:8: in <module>
2025-01-14T20:56:47.3225261Z     from tardis.plasma.equilibrium.rates import (
2025-01-14T20:56:47.3225627Z tardis/plasma/equilibrium/rates/__init__.py:5: in <module>
2025-01-14T20:56:47.3226076Z     from tardis.plasma.equilibrium.rates.collisional_ionization_rates import (
2025-01-14T20:56:47.3227175Z E   ImportError: cannot import name 'CollisionalIonizationSolver' from 'tardis.plasma.equilibrium.rates.collisional_ionization_rates' (/home/runner/work/tardis/tardis/tardis/plasma/equilibrium/rates/collisional_ionization_rates.py)
2025-01-14T20:56:47.3228210Z =============================== warnings summary ===============================
2025-01-14T20:56:47.3228531Z tardis/io/configuration/config_validator.py:6
2025-01-14T20:56:47.3229091Z tardis/io/configuration/config_validator.py:6
2025-01-14T20:56:47.3229774Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-01-14T20:56:47.3230262Z   
2025-01-14T20:56:47.3231518Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-01-14T20:56:47.3233832Z 
2025-01-14T20:56:47.3234239Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-01-14T20:56:47.3235394Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-01-14T20:56:47.3236259Z   
2025-01-14T20:56:47.3236631Z   Jupyter is migrating its paths to use standard platformdirs
2025-01-14T20:56:47.3237172Z   given by the platformdirs library.  To remove this warning and
2025-01-14T20:56:47.3237570Z   see the appropriate new directories, set the environment variable
2025-01-14T20:56:47.3237960Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-01-14T20:56:47.3238338Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-01-14T20:56:47.3238580Z 
2025-01-14T20:56:47.3238780Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-01-14T20:56:47.3239062Z 
2025-01-14T20:56:47.3239227Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-01-14T20:56:47.3239797Z Coverage HTML written to dir coverage_html_report
2025-01-14T20:56:47.3240110Z Coverage XML written to file coverage.xml
2025-01-14T20:56:47.3240293Z 
2025-01-14T20:56:47.3240415Z =========================== short test summary info ============================
2025-01-14T20:56:47.3241512Z ERROR tardis/plasma/equilibrium/tests - ImportError: cannot import name 'CollisionalIonizationSolver' from 'tardis.plasma.equilibrium.rates.collisional_ionization_rates' (/home/runner/work/tardis/tardis/tardis/plasma/equilibrium/rates/collisional_ionization_rates.py)
2025-01-14T20:56:47.3242628Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-01-14T20:56:47.3242997Z ================== 2 deselected, 3 warnings, 1 error in 9.04s ==================
2025-01-14T20:56:47.9859175Z ##[error]Process completed with exit code 2.
